version: '3.8'

services:
  bingle-shop:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 5261:5252
    depends_on:
      - automation_db
      - automation_testing_migration
      - test_db
      - test_migration
    env_file:
      - .env.production
      - .env.test
    command: sh -c "npm run start"
    volumes:
      - type: volume
        source: automation_module_volume
        target: /app/node_modules
      - type: bind
        source: .
        target: /app
  
  automation_testing_migration:
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - automation_db
    env_file:
      - .env.production
    command: sh -c "npm run db:migrate:prod && npm run db:seed:prod"
    # command: sh -c "npm run db:migrate:development"
    restart: on-failure

  test_migration:
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - test_db
    env_file:
      - .env.test
    command: sh -c "npm run db:migrate:test"
    # command: sh -c "npm run db:migrate:development"
    restart: on-failure

  automation_db:
    image: postgres:14
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=DB_NAME=BingleShop

  test_db:
    image: postgres:14
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=DB_NAME=BingleShop-test
  
  
  


volumes:
  automation_module_volume:

  #automation_db